[[pages]]
path = "app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/1_ğŸ“¥_Batch_Receipt.py"
name = "Production Run"
icon = "ğŸ­"

[[pages]]
path = "pages/2_ğŸ“¦_Inventory.py"
name = "Inventory"
icon = "ğŸ“¦"

[[pages]]
path = "pages/3_ğŸ›’_Sales.py"
name = "Sales"
icon = "ğŸ›’"

[[pages]]
path = "pages/4_âœ…_Batch_Close_&_Loss.py"
name = "Batch Close & Loss"
icon = "âœ…"

[[pages]]
path = "pages/5_ğŸ§ª_Data_Management.py"
name = "Data Management"
icon = "ğŸ§ª"

[[pages]]
path = "pages/6_ğŸ“Š_Reports.py"
name = "Reports"
icon = "ğŸ“Š"
